apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-sijo
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0006-tenant/tkrw-pr712-0075-0006-app/devfile-sample-sijo@sha256:3453ce24789a5b2c417fad59250be6cb6cdae5bde9b25c538a5f625dfea4bcd3
        name: my-nodejs
        resources: {}
status: {}
